Error messages in Responses should be an array of string instead of a single string
Teal-Connect/docs pull request #21
Opened 2024-03-30 13:35 UTC by luchesar

2024-03-31 19:26 UTC, arun-singh requested changes

2024-03-31 19:26 UTC, arun-singh commented on api-reference/openapi.yml
> +          description: A array of msesages describing the not found errors
Type in messages

2024-03-31 19:26 UTC, arun-singh commented on api-reference/openapi.yml
> +          description: An array of msesages describing the conflict errors
Typo here too

2024-03-31 19:26 UTC, arun-singh commented on api-reference/openapi.yml
> +          description: An array messages describing the errors
array **of**

2024-04-01 06:49 UTC, luchesar commented on api-reference/openapi.yml
> +          description: A array of msesages describing the not found errors
fixed

2024-04-01 06:54 UTC, merged