Update webhook dedicated page
Teal-Connect/docs pull request #26
Opened 2024-04-11 17:57 UTC by arun-singh

Updated webhooks to be more like https://argyle.com/docs/api-guide/webhooks.

Some things we can't add yet like wildcards for event subscriptions or the static IPs to whitelist. 

Didn't add the code snippet for listening and verifying.

2024-04-11 19:36 UTC, luchesar requested changes

2024-04-11 19:36 UTC, luchesar commented on api-reference/webhooks.mdx
> +If the optional `secret` was provided in the webhook subscription, it can be used to validate incoming webhook signatures, ensuring data integrity and authenticity.
Is it worth mentioning similar higlighted fact as:
<img width="789" alt="image" src="https://github.com/Teal-Connect/docs/assets/753245/60f058aa-dcc4-4824-a26b-9adf81230b45">

2024-04-11 19:36 UTC, luchesar commented on api-reference/webhooks.mdx
> +
Is it worth adding the signature verification code example:
```js
const http = require('http');
const crypto = require('crypto');

const serverPort = 80
const requestListener = function (req, res) {
    const client_secret = 'my little secret';
    var requestBody = '';
    req.on('readable', () => {
        var read = req.read()
        if(read != null) {
        requestBody += read;
        }
    });
    req.on('end', () => {
        // Make sure to use the raw requestBody when validating the signature.
        signature = crypto.createHmac('sha512',client_secret).update(requestBody).digest('hex');
        console.log('Signature:' + signature);
        res.writeHead(200);
        res.end(signature);
    })
}
const server = http.createServer(requestListener);
server.listen(serverPort);
```

2024-04-14 20:18 UTC, arun-singh commented on api-reference/webhooks.mdx
> +If the optional `secret` was provided in the webhook subscription, it can be used to validate incoming webhook signatures, ensuring data integrity and authenticity.
We have 

`Webhooks are system-wide, not limited to specific users or accounts, enhancing your application's responsiveness.` 

above but have changed it to:

`Webhooks are system-wide meaning subscriptions are not limited to specific users or accounts. For example, if any user updates their payroll with the `user-payroll-submitted` subscription enabled, 
a webbook will be delivered with the respective user information enclosed.`

2024-04-14 20:18 UTC, arun-singh commented on api-reference/webhooks.mdx
> +
THink its slightly overkill for now

2024-04-17 11:09 UTC, luchesar approved these changes
LGTM

2024-04-17 11:13 UTC, merged